# Generated by Django 3.1.1 on 2021-06-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='score_avg',
            field=models.FloatField(default=0, max_length=32),
        ),
    ]
