# Generated by Django 3.1.1 on 2021-05-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='protection',
            field=models.CharField(default='no_protection', max_length=128),
        ),
    ]
