# Generated by Django 3.1.1 on 2021-06-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='score',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='image',
            field=models.ImageField(upload_to='books'),
        ),
        migrations.AlterField(
            model_name='illustrationpostrequest',
            name='image',
            field=models.ImageField(upload_to='books'),
        ),
    ]
