# Generated by Django 3.1.1 on 2021-05-20 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_illustrationrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IllustrationRequest',
            new_name='IllustrationPostRequest',
        ),
        migrations.CreateModel(
            name='IllustrationDeleteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illustration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.illustration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
