# Generated by Django 3.1.1 on 2021-04-01 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 23, 15, 49, 485693)),
        ),
    ]
