# Generated by Django 3.1.1 on 2021-06-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210607_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.JSONField(max_length=128),
        ),
    ]
