# Generated by Django 3.1.1 on 2021-05-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_edits',
            field=models.IntegerField(default=0),
        ),
    ]
