# Generated by Django 3.1.1 on 2021-06-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210607_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='score',
            new_name='score_dict',
        ),
    ]
