# Generated by Django 3.1.1 on 2021-04-01 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(default=datetime.date(2000, 2, 2)),
        ),
    ]
