# Generated by Django 3.1.1 on 2021-05-03 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_user_num_edits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='num_edits',
            new_name='contributions',
        ),
    ]
