# Generated by Django 3.1.1 on 2021-06-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210607_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='score_dict',
            new_name='score',
        ),
    ]
