# Generated by Django 3.1.1 on 2021-05-16 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210515_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.book')),
                ('date', models.DateField(auto_now=True)),
                ('change', models.CharField(max_length=24)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('books.book',),
        ),
    ]
