# Generated by Django 3.1.1 on 2021-06-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210607_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.JSONField(default=dict, max_length=128),
        ),
    ]
