# Generated by Django 3.1.1 on 2021-04-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210407_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='characters',
            field=models.JSONField(blank=True, default='', max_length=528),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.JSONField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.JSONField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='keywords',
            field=models.JSONField(blank=True, default='', max_length=528),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='original_title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
