# Generated by Django 3.1.1 on 2021-04-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210413_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='characters',
            field=models.JSONField(default={}, max_length=528),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.JSONField(default={}, max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.JSONField(default={}, max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='keywords',
            field=models.JSONField(default={}, max_length=528),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_title',
            field=models.CharField(default={}, max_length=128),
        ),
    ]
