# Generated by Django 3.1.1 on 2021-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210413_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='characters',
            field=models.JSONField(blank=True, max_length=528),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.JSONField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.JSONField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='keywords',
            field=models.JSONField(blank=True, max_length=528),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
