# Generated by Django 3.1.1 on 2021-04-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='none', max_length=175),
            preserve_default=False,
        ),
    ]
