# Generated by Django 3.1.1 on 2021-04-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20210419_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='characters',
            field=models.JSONField(max_length=528),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.JSONField(max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='keywords',
            field=models.JSONField(max_length=528),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_title',
            field=models.CharField(max_length=128),
        ),
    ]
