# Generated by Django 3.1.1 on 2021-04-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20210419_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='book',
            name='characters',
            field=models.JSONField(default=dict, max_length=528),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.JSONField(default=dict, max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.JSONField(default=dict, max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='keywords',
            field=models.JSONField(default=dict, max_length=528),
        ),
    ]
